name: 'Close stale issues and PRs'
on:
  schedule:
    #    - cron: '30 1 * * *'
    - cron: '0 19 * * *'
  push:
    paths:
      - .github/workflows/stale.yml
    branches:
      - main

jobs:
  stale:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - uses: actions/stale@v7
        with:
          # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within the next 7 days.
            Please check if the issue is still relevant in the most current version of the adapter
            and tell us. Also check that all relevant details, logs and reproduction steps
            are included and update them if needed.
            Thank you for your contributions.
          
            Dieses Problem wurde automatisch als veraltet markiert, da es in letzter Zeit keine Aktivitäten gab.
            Es wird geschlossen, wenn nicht innerhalb der nächsten 7 Tage weitere Aktivitäten stattfinden.
            Bitte überprüft, ob das Problem auch in der aktuellsten Version des Adapters noch relevant ist,
            und teilt uns dies mit. Überprüft auch, ob alle relevanten Details, Logs und Reproduktionsschritte
            enthalten sind bzw. aktualisiert diese.
            Vielen Dank für Eure Unterstützung.
        
          # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
          close-issue-message: >
            This issue has been automatically closed because of inactivity. Please open a new
            issue if still relevant and make sure to include all relevant details, logs and reproduction steps.
            Thank you for your contributions.
          
            Dieses Problem wurde aufgrund von Inaktivität automatisch geschlossen. Bitte öffnet ein
            neues Issue, falls dies noch relevant ist und stellt sicher das alle relevanten Details,
            Logs und Reproduktionsschritte enthalten sind.
            Vielen Dank für Eure Unterstützung.
        
          # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
          days-before-stale: 30
        
          # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
          days-before-close: 7
        
          #
          close-issue-reason: not_planned
        
          # The label to apply when an issue is stale.
          stale-issue-label: 'wontfix, outdated'
        
          # The label to apply when an issue is closed.
          close-issue-label: 'closed'
        
          # The labels that mean an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2").
          exempt-issue-labels: 'enhancement, work-in-progress, security, bug'
        
          # The maximum number of operations per run, used to control rate limiting (GitHub API CRUD related).
          operations-per-run: 30
        
          # Remove stale labels from issues and pull requests when they are updated or commented on.
          remove-stale-when-updated: true
        
          # A comma delimited list of labels to remove when a stale issue or pull request receives activity and has the stale-issue-label or stale-pr-label removed from it.
          labels-to-remove-when-unstale: 'wontfix, outdated'
        
          # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        
          # Optional parameters below.
        
          # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
          # stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
        
          # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
          # close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
        
          # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues as stale automatically. Override "days-before-stale" option regarding only the issues.
          # days-before-issue-stale: 20
        
          # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. Override "days-before-stale" option regarding only the pull requests.
          # days-before-pr-stale: 40
        
          # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
          # days-before-issue-close: 5
        
          # The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests. Override "days-before-close" option regarding only the pull requests.
          # days-before-pr-close: 10
        
          # The label to apply when a pull request is stale.
          # stale-pr-label: 'wontfix, outdated'
        
          # The label to apply when a pull request is closed.
          # close-pr-label: 'closed'
        
          # The labels that mean a pull request is exempt from being marked as stale. Separate multiple labels with commas (eg. "label1,label2").
          # exempt-pr-labels: 'enhancement,work-in-progress,security,bug'
        
          # Remove stale labels from issues when they are updated or commented on. Override "remove-stale-when-updated" option regarding only the issues.
          # remove-issue-stale-when-updated: true
        
          # Remove stale labels from pull requests when they are updated or commented on. Override "remove-stale-when-updated" option regarding only the pull requests.
          # remove-pr-stale-when-updated: true
        
          # A comma delimited list of labels to add when a stale issue or pull request receives activity and has the stale-issue-label or stale-pr-label removed from it.
          # labels-to-add-when-unstale: 'work-in-progress'
        
          # Any update (update/comment) can reset the stale idle time on the issues and pull requests. Set to false to only consider pull request/issue updates.
          # ignore-updates: false
        
          # Any update (update/comment) can reset the stale idle time on the issues. Override "ignore-updates" option regarding only the issues.
          # ignore-issue-updates: false
        
          # Any update (update/comment) can reset the stale idle time on the pull requests. Override "ignore-updates" option regarding only the pull requests.
          # ignore-pr-updates: true
